import json
import os
import subprocess
import numpy as np

# 1. SETUP PATHS
script_dir = os.path.dirname(os.path.abspath(__file__))

ads_script = "PSA(ads,New).py" 
des_script = "PSA(Depressurization).py"
rep_script = "PSA(Repressurization).py"

ads_path = os.path.join(script_dir, ads_script)
des_path = os.path.join(script_dir, des_script)
rep_path = os.path.join(script_dir, rep_script)

def wipe_states():
    print("\n--- Cleaning up old bed states ---")
    files_to_delete = [
        "adsorption_end_state.npz", 
        "desorption_end_state.npz", 
        "previous_cycle_state.npz",
        "repressurization_end_state.npz"
    ]
    for file in files_to_delete:
        file_path = os.path.join(script_dir, file)
        if os.path.exists(file_path):
            os.remove(file_path)
            print(f"🗑️ Deleted: {file}")
    print("✨ Bed is clean.")

# --- 1.2 DEFINE INITIAL MASTER PARAMETERS ---
Phigh = 15 * 101325  
Plow = 1 * 101325   
PFratio = 0.09 # Increased purge for realistic CSS stability
L=12 #m
d =3 #m
master_params = {
    # Bed & System Parameters
    "L": L,
    "T": 30 + 273.15,
    "R": 8.314,
    "P_high": Phigh,
    "P_low": Plow,
    "d": d,
    "Nsets": 3,
    "ratio_layer1": 0.8,
    "purge_fraction": PFratio,
    "N": 100,
    "dp": 0.002,
    "mu": 1.135086e-05,
    "P_atm_Pa": 101325.0,
    "eps_1": 0.35,
    "eps_2": 0.35,
    "rho_s_1": 850,
    "rho_s_2": 1160,
    
    # Ratios used for auto-scaling phase times
    "Adsorption_Ratio": 0.50,
    "Blowdown_Ratio": 0.15,
    "Purge_Ratio": 0.25, # Adjusted to match the PFratio bump
    'Repress_Ratio': 0.05, # New ratio for repressurization time
    
   # Time Parameters: 
    "t_ads_start": 0,
    "t_ads_end": 2000, 
    "t_op_ads": 400, #Adsorption (Will be optimized by Scout)
    "t_ads_safety_ratio": 0.9,
    "tau_bd": 30.0
}

config_path = os.path.join(script_dir, "master_config.json")
with open(config_path, "w") as f:
    json.dump(master_params, f, indent=4)

# =============================================================================
# PHASE A: THE SCOUT RUN (Cycle 0)
# =============================================================================
print("\n" + "="*50)
print(" PHASE A: SCOUT RUN (FINDING BREAKTHROUGH)")
print("="*50)
wipe_states() 

env = os.environ.copy()
env["MPLBACKEND"] = "Agg"
env["PSA_CYCLE"] = "0"
env["RUN_TYPE"] = "SCOUT" # Tells the Adsorption script to optimize the config

subprocess.run(["python3", ads_path], env=env, check=True)

# Read the newly optimized times generated by the Scout run
with open(config_path, "r") as f:
    optimized_config = json.load(f)

print(f"\n---> Scout Complete. Optimized Adsorption Time: {optimized_config['t_op_ads']:.1f} s <---")

# =============================================================================
# PHASE B: THE CYCLIC STEADY STATE (CSS) LOOP
# =============================================================================
wipe_states() # Critical: Wipe the saturated Scout bed so Cycle 1 starts clean!

max_cycles = 50
convergence_tolerance = 8e-3
env["RUN_TYPE"] = "CSS" # Tells the Adsorption script to stop at t_op_ads

for cycle in range(1, max_cycles + 1):
    print(f"\n" + "="*50)
    print(f" STARTING CYCLE {cycle} (CSS LOOP)")
    print("="*50)

    env["PSA_CYCLE"] = str(cycle)
    
    subprocess.run(["python3", ads_path], env=env, check=True)
    subprocess.run(["python3", des_path], env=env, check=True)
    subprocess.run(["python3", rep_path], env=env, check=True)

    state_file = os.path.join(script_dir, "repressurization_end_state.npz")
    prev_state_file = os.path.join(script_dir, "previous_cycle_state.npz")

    if os.path.exists(prev_state_file) and os.path.exists(state_file):
        current_q = np.load(state_file)['q_end']
        previous_q = np.load(prev_state_file)['q_end']
        
        residual = np.linalg.norm(current_q - previous_q) / np.linalg.norm(previous_q)
        print(f"\n---> Cycle {cycle} Convergence Residual: {residual:.4e} <---")
        
        if residual < convergence_tolerance:
            print("\n✅ CYCLIC STEADY STATE REACHED!")
            
            # --- CAPEX & OPEX TIMING DIAGNOSTICS ---
            # Reload the config to grab the SCOUT-optimized times
            with open(config_path, "r") as f:
                final_config = json.load(f)
                
            final_t_ads = final_config.get("t_op_ads", 0)
            final_t_bd = final_config.get("t_blowdown_end", 0)
            final_t_des = final_config.get("tf_des", 0)
            final_t_rep = final_config.get("t_rep", 60.0)
            
            total_cycle_time = final_t_ads + final_t_bd + final_t_des + final_t_rep
            
            print("\n" + "="*50)
            print(" FINAL CSS TIMING METRICS (For CapEx/OpEx)")
            print("="*50)
            print(f"Adsorption Time:         {final_t_ads:>6.1f} s")
            print(f"Depressurization (BD):   {final_t_bd:>6.1f} s")
            print(f"Desorption (Purge):      {final_t_des:>6.1f} s")
            print(f"Repressurization:        {final_t_rep:>6.1f} s")
            print("-" * 50)
            print(f"TOTAL CYCLE TIME:        {total_cycle_time:>6.1f} s")
            print(f"Total Cycles Simulated:  {cycle}")
            print("="*50 + "\n")
            
            # Save these metrics to a text file for easy reference later
            with open(os.path.join(script_dir, "results", "CSS_Timing_Report.txt"), "w") as f:
                f.write("FINAL CSS TIMING METRICS\n")
                f.write(f"Adsorption:     {final_t_ads:.1f} s\n")
                f.write(f"Blowdown:       {final_t_bd:.1f} s\n")
                f.write(f"Purge:          {final_t_des:.1f} s\n")
                f.write(f"Repress:        {final_t_rep:.1f} s\n")
                f.write(f"Total Cycle:    {total_cycle_time:.1f} s\n")
                f.write(f"Cycles Simulated: {cycle}\n")
                f.write('' + "="*30 + "\n")
                f.write('COLUMN SPECS:\n')
                f.write(f"Bed Length (L): {final_config['L']} m\n")
                f.write(f"Bed Diameter (d): {final_config['d']} m\n")
                f.write(f'L/D Ratio: {final_config["L"] / final_config["d"]:.3f}\n')
                f.write(f'Number of Pairs: {final_config["Nsets"]}\n')

            break # Exit the CSS loop
    else:
        print("\n---> Cycle 1 complete. Establishing baseline. <---")
    
    if os.path.exists(state_file):
        data = np.load(state_file)
        np.savez(prev_state_file, q_end=data['q_end'])

# =============================================================================
# PHASE C: THE FINAL DIAGNOSTIC RUN
# =============================================================================
print("\n" + "="*50)
print(" PHASE C: FINAL DIAGNOSTIC RUN (CSS BREAKTHROUGH)")
print("="*50)

env["PSA_CYCLE"] = "FINAL"
env["RUN_TYPE"] = "FINAL" # Tells Adsorption to run to 1500s on the CSS bed

subprocess.run(["python3", ads_path], env=env, check=True)
print("\n🎉 AUTOMATED WORKFLOW COMPLETE. Check the 'results' folder.")
